version: '3.8'

services:
  postgres161:
    image: postgres:16.1
    container_name: postgres161-container
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5416:5432"
    networks:
      - mynetwork
    volumes:
      - postgres161_data:/var/lib/postgresql/data
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres161_data:
